### PR TITLE
Don't keep per-input state in the `Predictor` class

### LINKED ISSUE #12: Thread-safety of `Predictor.predict`
It looks like `Predictor.predict` is not yet thread-safe, so it would not work in a typical multi-threaded / async deployment. Might need some refactoring...

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #12 

This is the first step for making the `Predictor` thread-safe.

* Remove the `set_input` method and instead pass the per-input state
  around explicitly, mostly in the `Predictor.predict` method
* Don't assign results to a `self.results` dict; instead, only return
  results from `Predictor.predict`
* Set `Predictor.conv_angle_norm` once after loading the models, as it
  doesn't change per input (yet?)

## TODO

- [x] Use thread-local `Interpreter` instances, figure out how to share model between multiple interpreters

### CODE REVIEW

**Comment by sk1p** [comment]
@MichaelO1993 I've fixed the obvious issues with keeping state on `self` now - I'm still stumped on the TODO item mentioned above. Do you know if there is a method of loading a model independent of the `Interpreter`, which can then be passed into the `Interpreter` constructor as `model_content`? I found `tf.lite.tools.flatbuffer_utils.read_model`, but that doesn't seem to be compatible with usage as `model_content`.

**Comment by uellue** [comment]
@sk1p The source code and docstring of tf.lite.Interpreter can help perhaps? https://github.com/tensorflow/tensorflow/blob/8661a0a253352a2b89143e2c8c56d83eb53ea875/tensorflow/lite/python/interpreter.py#L354-L393

Maybe one could instantiate the interpreter once with a path on start-up and then extract the model from there?

**Comment by sk1p** [comment]
> @sk1p The source code and docstring of tf.lite.Interpreter can help perhaps? https://github.com/tensorflow/tensorflow/blob/8661a0a253352a2b89143e2c8c56d83eb53ea875/tensorflow/lite/python/interpreter.py#L354-L393

Sadly not - I don't see how to load a model directly from a flatbuffer file, everything either deals with conversion from a different format, or the interpreter is constructed directly from the file.

> Maybe one could instantiate the interpreter once with a path on start-up and then extract the model from there?

I tried this, I didn't find a method to extract the underlying model from an interpreter.

**Comment by sk1p** [comment]
This may be a hint that it is indeed possible:

> `tflite_model` can be saved to a file and loaded later, or directly into the
  `Interpreter`. Since TensorFlow Lite pre-plans tensor allocations to optimize
  inference, the user needs to call `allocate_tensors()` before any inference.

"and loaded later" - but there is no indication _how_.

**Comment by sk1p** [comment]
> https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/lite/tools/serialization/README.md

Yeah, in C++ the API is more explicit, there I basically found directly applicable examples... I'm reading the tf lite source code right now to see if/how this is possible from Python

**Comment by uellue** [comment]
Hm, do we have a plan B in case it gets too complicated? Is the inference multithreaded, actually?

**Comment by uellue** [comment]
We could just serialize the inference part of requests with a mutex. Should be enough for the demo, right?

**Comment by sk1p** [comment]
Hm, looking at flat buffers, it's possible that they are already implicitly shared by memory mapping, let me check...

> Hm, do we have a plan B in case it gets too complicated?

Yes, we can serialize inference (which would be a bit sad...)

>Is the inference multithreaded, actually?

It's possible that inference is multi threaded, yes - but the preprocessing is not, so I would prefer to have per-request multi-threading still.

**Comment by sk1p** [comment]
> Hm, looking at flat buffers, it's possible that they are already implicitly shared by memory mapping, let me check...

Excerpt from `/proc/<pid>/maps`: 


```
7fad31347000-7fad36efd000 r--s 00000000 fe:00 17495095                   /home/alex/source/PACBED-CNN/PACBED-CNN-data/data/1/models/0/Thickness.tflite
7fad36efd000-7fad3bd5d000 rw-p 00000000 00:00 0 
7fad3bd5d000-7fad418ba000 r--s 00000000 fe:00 17495091                   /home/alex/source/PACBED-CNN/PACBED-CNN-data/data/1/models/0/Mistilt.tflite
7fad418ba000-7fad4671a000 rw-p 00000000 00:00 0 
7fad4671a000-7fad4c273000 r--s 00000000 fe:00 17495093                   /home/alex/source/PACBED-CNN/PACBED-CNN-data/data/1/models/0/Scale.tflite
7fad4c273000-7fad510d3000 rw-p 00000000 00:00 0 
7fad510d3000-7fad56c8a000 r--s 00000000 fe:00 16830639                   /home/alex/source/PACBED-CNN/PACBED-CNN-data/data/0/models/0/Thickness.tflite
7fad56c8a000-7fad5baea000 rw-p 00000000 00:00 0 
7fad5baea000-7fad61647000 r--s 00000000 fe:00 16830642                   /home/alex/source/PACBED-CNN/PACBED-CNN-data/data/0/models/0/Mistilt.tflite
7fad61647000-7fad664a7000 rw-p 00000000 00:00 0 
7fad664a7000-7fad6c000000 r--s 00000000 fe:00 16830637                   /home/alex/source/PACBED-CNN/PACBED-CNN-data/data/0/models/0/Scale.tflite
```

So if the code doesn't do anything stupid, i.e. copies, we should be able to cheaply create multiple interpreters for a single model without any additional work.

**Comment by uellue** [comment]
> Yes, we can serialize inference (which would be a bit sad...

IF inference is multithreaded this could actually be faster. :-)

**Comment by uellue** [comment]
> So if the code doesn't do anything stupid, i.e. copies, we should be able to cheaply create multiple interpreters for a single model without any additional work.

Oh nice!

**Comment by sk1p** [comment]
> IF inference is multithreaded this could actually be faster. :-)

Could, yes - I guess one would need to benchmark this, as it can be non-obvious how the "internal" multi-threading of inference scales vs. the scaling of per-request multi-threading. My guess would be that the work for a single inference is not enough to properly utilize many cores.

**Comment by sk1p** [comment]
> Ok, that sounds like a job for the second stage. :-) What about just creating an Interpreter per request for now, and if that is too slow we serialize with a Mutex?

We can keep the interpreters around as thread locals - no need to re-create for each request.

**Comment by uellue** [comment]
Test looks good, performance as well. Thx. merging! :-)

**Pull request merged**
